main: main.cpp
	clang++-6.0 -o main -I World -I Tracers -I Utilities -I GeometricObjects *.cpp */*.cpp
#   compiler, exe name, include all folders, compile all cpp in current folder and all sub folders